// Generated by scripts/update-languages.mjs from GitHub Linguist. Do not edit by hand.
export interface LanguageData {
	name: string;
	color: string;
}

export const LANGUAGES: Record<string, LanguageData> = {
	"1c enterprise": {
		"name": "1C Enterprise",
		"color": "#814CCC"
	},
	"2-dimensional array": {
		"name": "2-Dimensional Array",
		"color": "#38761D"
	},
	"4d": {
		"name": "4D",
		"color": "#004289"
	},
	"abap": {
		"name": "ABAP",
		"color": "#E8274B"
	},
	"abap cds": {
		"name": "ABAP CDS",
		"color": "#555e25"
	},
	"abl": {
		"name": "OpenEdge ABL",
		"color": "#5ce600"
	},
	"abuild": {
		"name": "Alpine Abuild",
		"color": "#0D597F"
	},
	"acfm": {
		"name": "Adobe Font Metrics",
		"color": "#fa0f00"
	},
	"ackrc": {
		"name": "Option List",
		"color": "#476732"
	},
	"aconf": {
		"name": "ApacheConf",
		"color": "#d12127"
	},
	"actionscript": {
		"name": "ActionScript",
		"color": "#882B0F"
	},
	"actionscript 3": {
		"name": "ActionScript",
		"color": "#882B0F"
	},
	"actionscript3": {
		"name": "ActionScript",
		"color": "#882B0F"
	},
	"ad block": {
		"name": "Adblock Filter List",
		"color": "#800000"
	},
	"ad block filters": {
		"name": "Adblock Filter List",
		"color": "#800000"
	},
	"ada": {
		"name": "Ada",
		"color": "#02f88c"
	},
	"ada2005": {
		"name": "Ada",
		"color": "#02f88c"
	},
	"ada95": {
		"name": "Ada",
		"color": "#02f88c"
	},
	"adb": {
		"name": "Adblock Filter List",
		"color": "#800000"
	},
	"adblock": {
		"name": "Adblock Filter List",
		"color": "#800000"
	},
	"adblock filter list": {
		"name": "Adblock Filter List",
		"color": "#800000"
	},
	"adobe composite font metrics": {
		"name": "Adobe Font Metrics",
		"color": "#fa0f00"
	},
	"adobe font metrics": {
		"name": "Adobe Font Metrics",
		"color": "#fa0f00"
	},
	"adobe multiple font metrics": {
		"name": "Adobe Font Metrics",
		"color": "#fa0f00"
	},
	"advpl": {
		"name": "xBase",
		"color": "#403a40"
	},
	"agda": {
		"name": "Agda",
		"color": "#315665"
	},
	"ags": {
		"name": "AGS Script",
		"color": "#B9D9FF"
	},
	"ags script": {
		"name": "AGS Script",
		"color": "#B9D9FF"
	},
	"ahk": {
		"name": "AutoHotkey",
		"color": "#6594b9"
	},
	"aidl": {
		"name": "AIDL",
		"color": "#34EB6B"
	},
	"aiken": {
		"name": "Aiken",
		"color": "#640ff8"
	},
	"al": {
		"name": "AL",
		"color": "#3AA2B5"
	},
	"algol": {
		"name": "ALGOL",
		"color": "#D1E0DB"
	},
	"alloy": {
		"name": "Alloy",
		"color": "#64C800"
	},
	"alpine abuild": {
		"name": "Alpine Abuild",
		"color": "#0D597F"
	},
	"altium": {
		"name": "Altium Designer",
		"color": "#A89663"
	},
	"altium designer": {
		"name": "Altium Designer",
		"color": "#A89663"
	},
	"amfm": {
		"name": "Adobe Font Metrics",
		"color": "#fa0f00"
	},
	"ampl": {
		"name": "AMPL",
		"color": "#E6EFBB"
	},
	"angelscript": {
		"name": "AngelScript",
		"color": "#C7D7DC"
	},
	"answer set programming": {
		"name": "Answer Set Programming",
		"color": "#A9CC29"
	},
	"ant build system": {
		"name": "Ant Build System",
		"color": "#A9157E"
	},
	"antlers": {
		"name": "Antlers",
		"color": "#ff269e"
	},
	"antlr": {
		"name": "ANTLR",
		"color": "#9DC3FF"
	},
	"apache": {
		"name": "ApacheConf",
		"color": "#d12127"
	},
	"apacheconf": {
		"name": "ApacheConf",
		"color": "#d12127"
	},
	"apex": {
		"name": "Apex",
		"color": "#1797c0"
	},
	"api blueprint": {
		"name": "API Blueprint",
		"color": "#2ACCA8"
	},
	"apkbuild": {
		"name": "Alpine Abuild",
		"color": "#0D597F"
	},
	"apl": {
		"name": "APL",
		"color": "#5A8164"
	},
	"apollo guidance computer": {
		"name": "Apollo Guidance Computer",
		"color": "#0B3D91"
	},
	"apples": {
		"name": "AppleScript",
		"color": "#101F1F"
	},
	"applescript": {
		"name": "AppleScript",
		"color": "#101F1F"
	},
	"arc": {
		"name": "Arc",
		"color": "#aa2afe"
	},
	"arexx": {
		"name": "REXX",
		"color": "#d90e09"
	},
	"as3": {
		"name": "ActionScript",
		"color": "#882B0F"
	},
	"ascii stl": {
		"name": "STL",
		"color": "#373b5e"
	},
	"asciidoc": {
		"name": "AsciiDoc",
		"color": "#73a0c5"
	},
	"asm": {
		"name": "Assembly",
		"color": "#6E4C13"
	},
	"asp": {
		"name": "Classic ASP",
		"color": "#6a40fd"
	},
	"asp.net": {
		"name": "ASP.NET",
		"color": "#9400ff"
	},
	"aspectj": {
		"name": "AspectJ",
		"color": "#a957b0"
	},
	"aspx": {
		"name": "ASP.NET",
		"color": "#9400ff"
	},
	"aspx-vb": {
		"name": "ASP.NET",
		"color": "#9400ff"
	},
	"assembly": {
		"name": "Assembly",
		"color": "#6E4C13"
	},
	"astro": {
		"name": "Astro",
		"color": "#ff5a03"
	},
	"asymptote": {
		"name": "Asymptote",
		"color": "#ff0000"
	},
	"ats": {
		"name": "ATS",
		"color": "#1ac620"
	},
	"ats2": {
		"name": "ATS",
		"color": "#1ac620"
	},
	"au3": {
		"name": "AutoIt",
		"color": "#1C3552"
	},
	"augeas": {
		"name": "Augeas",
		"color": "#9CC134"
	},
	"autohotkey": {
		"name": "AutoHotkey",
		"color": "#6594b9"
	},
	"autoit": {
		"name": "AutoIt",
		"color": "#1C3552"
	},
	"autoit3": {
		"name": "AutoIt",
		"color": "#1C3552"
	},
	"autoitscript": {
		"name": "AutoIt",
		"color": "#1C3552"
	},
	"avro idl": {
		"name": "Avro IDL",
		"color": "#0040FF"
	},
	"awk": {
		"name": "Awk",
		"color": "#c30e9b"
	},
	"b (formal method)": {
		"name": "B (Formal Method)",
		"color": "#8aa8c5"
	},
	"b3d": {
		"name": "BlitzBasic",
		"color": "#00FFAE"
	},
	"b4x": {
		"name": "B4X",
		"color": "#00e4ff"
	},
	"ballerina": {
		"name": "Ballerina",
		"color": "#FF5000"
	},
	"baml": {
		"name": "BAML",
		"color": "#a855f7"
	},
	"bash": {
		"name": "Shell",
		"color": "#89e051"
	},
	"basic": {
		"name": "BASIC",
		"color": "#ff0000"
	},
	"basic for android": {
		"name": "B4X",
		"color": "#00e4ff"
	},
	"bat": {
		"name": "Batchfile",
		"color": "#C1F12E"
	},
	"batch": {
		"name": "Batchfile",
		"color": "#C1F12E"
	},
	"batchfile": {
		"name": "Batchfile",
		"color": "#C1F12E"
	},
	"bazel": {
		"name": "Starlark",
		"color": "#76d275"
	},
	"be": {
		"name": "Berry",
		"color": "#15A13C"
	},
	"beef": {
		"name": "Beef",
		"color": "#a52f4e"
	},
	"berry": {
		"name": "Berry",
		"color": "#15A13C"
	},
	"bh": {
		"name": "Bluespec BH",
		"color": "#12223c"
	},
	"bibtex": {
		"name": "BibTeX",
		"color": "#778899"
	},
	"bicep": {
		"name": "Bicep",
		"color": "#519aba"
	},
	"bikeshed": {
		"name": "Bikeshed",
		"color": "#5562ac"
	},
	"bison": {
		"name": "Bison",
		"color": "#6A463F"
	},
	"bitbake": {
		"name": "BitBake",
		"color": "#00bce4"
	},
	"blade": {
		"name": "Blade",
		"color": "#f7523f"
	},
	"blitz3d": {
		"name": "BlitzBasic",
		"color": "#00FFAE"
	},
	"blitzbasic": {
		"name": "BlitzBasic",
		"color": "#00FFAE"
	},
	"blitzmax": {
		"name": "BlitzMax",
		"color": "#cd6400"
	},
	"blitzplus": {
		"name": "BlitzBasic",
		"color": "#00FFAE"
	},
	"bluespec": {
		"name": "Bluespec",
		"color": "#12223c"
	},
	"bluespec bh": {
		"name": "Bluespec BH",
		"color": "#12223c"
	},
	"bluespec bsv": {
		"name": "Bluespec",
		"color": "#12223c"
	},
	"bluespec classic": {
		"name": "Bluespec BH",
		"color": "#12223c"
	},
	"bmax": {
		"name": "BlitzMax",
		"color": "#cd6400"
	},
	"boo": {
		"name": "Boo",
		"color": "#d4bec1"
	},
	"boogie": {
		"name": "Boogie",
		"color": "#c80fa0"
	},
	"bplus": {
		"name": "BlitzBasic",
		"color": "#00FFAE"
	},
	"bqn": {
		"name": "BQN",
		"color": "#2b7067"
	},
	"brainfuck": {
		"name": "Brainfuck",
		"color": "#2F2530"
	},
	"brighterscript": {
		"name": "BrighterScript",
		"color": "#66AABB"
	},
	"brightscript": {
		"name": "Brightscript",
		"color": "#662D91"
	},
	"browserslist": {
		"name": "Browserslist",
		"color": "#ffd539"
	},
	"bru": {
		"name": "Bru",
		"color": "#F4AA41"
	},
	"bsdmake": {
		"name": "Makefile",
		"color": "#427819"
	},
	"bsv": {
		"name": "Bluespec",
		"color": "#12223c"
	},
	"buildstream": {
		"name": "BuildStream",
		"color": "#006bff"
	},
	"byond": {
		"name": "DM",
		"color": "#447265"
	},
	"bzl": {
		"name": "Starlark",
		"color": "#76d275"
	},
	"c": {
		"name": "C",
		"color": "#555555"
	},
	"c#": {
		"name": "C#",
		"color": "#178600"
	},
	"c++": {
		"name": "C++",
		"color": "#f34b7d"
	},
	"c3": {
		"name": "C3",
		"color": "#2563eb"
	},
	"cabal": {
		"name": "Cabal Config",
		"color": "#483465"
	},
	"cabal config": {
		"name": "Cabal Config",
		"color": "#483465"
	},
	"caddy": {
		"name": "Caddyfile",
		"color": "#22b638"
	},
	"caddyfile": {
		"name": "Caddyfile",
		"color": "#22b638"
	},
	"cadence": {
		"name": "Cadence",
		"color": "#00ef8b"
	},
	"cairo": {
		"name": "Cairo",
		"color": "#ff4a48"
	},
	"cairo zero": {
		"name": "Cairo Zero",
		"color": "#ff4a48"
	},
	"cake": {
		"name": "C#",
		"color": "#178600"
	},
	"cakescript": {
		"name": "C#",
		"color": "#178600"
	},
	"cameligo": {
		"name": "CameLIGO",
		"color": "#3be133"
	},
	"cangjie": {
		"name": "Cangjie",
		"color": "#00868B"
	},
	"cap cds": {
		"name": "CAP CDS",
		"color": "#0092d1"
	},
	"cap'n proto": {
		"name": "Cap'n Proto",
		"color": "#c42727"
	},
	"carbon": {
		"name": "Carbon",
		"color": "#222222"
	},
	"cask": {
		"name": "Emacs Lisp",
		"color": "#c065db"
	},
	"cds": {
		"name": "CAP CDS",
		"color": "#0092d1"
	},
	"ceylon": {
		"name": "Ceylon",
		"color": "#dfa535"
	},
	"cfc": {
		"name": "ColdFusion CFC",
		"color": "#ed2cd6"
	},
	"cfm": {
		"name": "ColdFusion",
		"color": "#ed2cd6"
	},
	"cfml": {
		"name": "ColdFusion",
		"color": "#ed2cd6"
	},
	"chapel": {
		"name": "Chapel",
		"color": "#8dc63f"
	},
	"chpl": {
		"name": "Chapel",
		"color": "#8dc63f"
	},
	"chuck": {
		"name": "ChucK",
		"color": "#3f8000"
	},
	"circom": {
		"name": "Circom",
		"color": "#707575"
	},
	"cirru": {
		"name": "Cirru",
		"color": "#ccccff"
	},
	"clarion": {
		"name": "Clarion",
		"color": "#db901e"
	},
	"clarity": {
		"name": "Clarity",
		"color": "#5546ff"
	},
	"classic asp": {
		"name": "Classic ASP",
		"color": "#6a40fd"
	},
	"classic qbasic": {
		"name": "QuickBASIC",
		"color": "#008080"
	},
	"classic quickbasic": {
		"name": "QuickBASIC",
		"color": "#008080"
	},
	"classic visual basic": {
		"name": "Visual Basic 6.0",
		"color": "#2c6353"
	},
	"clean": {
		"name": "Clean",
		"color": "#3F85AF"
	},
	"click": {
		"name": "Click",
		"color": "#E4E6F3"
	},
	"clipper": {
		"name": "xBase",
		"color": "#403a40"
	},
	"clips": {
		"name": "CLIPS",
		"color": "#00A300"
	},
	"clojure": {
		"name": "Clojure",
		"color": "#db5855"
	},
	"closure templates": {
		"name": "Closure Templates",
		"color": "#0d948f"
	},
	"cloud firestore security rules": {
		"name": "Cloud Firestore Security Rules",
		"color": "#FFA000"
	},
	"clue": {
		"name": "Clue",
		"color": "#0009b5"
	},
	"cmake": {
		"name": "CMake",
		"color": "#DA3434"
	},
	"coccinelle": {
		"name": "SmPL",
		"color": "#c94949"
	},
	"codeql": {
		"name": "CodeQL",
		"color": "#140f46"
	},
	"coffee": {
		"name": "CoffeeScript",
		"color": "#244776"
	},
	"coffee-script": {
		"name": "CoffeeScript",
		"color": "#244776"
	},
	"coffeescript": {
		"name": "CoffeeScript",
		"color": "#244776"
	},
	"coldfusion": {
		"name": "ColdFusion",
		"color": "#ed2cd6"
	},
	"coldfusion cfc": {
		"name": "ColdFusion CFC",
		"color": "#ed2cd6"
	},
	"coldfusion html": {
		"name": "ColdFusion",
		"color": "#ed2cd6"
	},
	"collada": {
		"name": "COLLADA",
		"color": "#F1A42B"
	},
	"commit": {
		"name": "Git Commit",
		"color": "#F44D27"
	},
	"common lisp": {
		"name": "Common Lisp",
		"color": "#3fb68b"
	},
	"common workflow language": {
		"name": "Common Workflow Language",
		"color": "#B5314C"
	},
	"component pascal": {
		"name": "Component Pascal",
		"color": "#B0CE4E"
	},
	"conf": {
		"name": "INI",
		"color": "#d1dbe0"
	},
	"containerfile": {
		"name": "Dockerfile",
		"color": "#384d54"
	},
	"cooklang": {
		"name": "Cooklang",
		"color": "#E15A29"
	},
	"coq": {
		"name": "Rocq Prover",
		"color": "#d0b68c"
	},
	"cperl": {
		"name": "Perl",
		"color": "#0298c3"
	},
	"cpp": {
		"name": "C++",
		"color": "#f34b7d"
	},
	"cql": {
		"name": "CQL",
		"color": "#006091"
	},
	"cron": {
		"name": "crontab",
		"color": "#ead7ac"
	},
	"cron table": {
		"name": "crontab",
		"color": "#ead7ac"
	},
	"crontab": {
		"name": "crontab",
		"color": "#ead7ac"
	},
	"crystal": {
		"name": "Crystal",
		"color": "#000100"
	},
	"csharp": {
		"name": "C#",
		"color": "#178600"
	},
	"cson": {
		"name": "CSON",
		"color": "#244776"
	},
	"csound": {
		"name": "Csound",
		"color": "#1a1a1a"
	},
	"csound document": {
		"name": "Csound Document",
		"color": "#1a1a1a"
	},
	"csound score": {
		"name": "Csound Score",
		"color": "#1a1a1a"
	},
	"csound-csd": {
		"name": "Csound Document",
		"color": "#1a1a1a"
	},
	"csound-orc": {
		"name": "Csound",
		"color": "#1a1a1a"
	},
	"csound-sco": {
		"name": "Csound Score",
		"color": "#1a1a1a"
	},
	"css": {
		"name": "CSS",
		"color": "#663399"
	},
	"csv": {
		"name": "CSV",
		"color": "#237346"
	},
	"cucumber": {
		"name": "Gherkin",
		"color": "#5B2063"
	},
	"cuda": {
		"name": "Cuda",
		"color": "#3A4E3A"
	},
	"cue": {
		"name": "CUE",
		"color": "#5886E1"
	},
	"curry": {
		"name": "Curry",
		"color": "#531242"
	},
	"cweb": {
		"name": "CWeb",
		"color": "#00007a"
	},
	"cwl": {
		"name": "Common Workflow Language",
		"color": "#B5314C"
	},
	"cylc": {
		"name": "Cylc",
		"color": "#00b3fd"
	},
	"cypher": {
		"name": "Cypher",
		"color": "#34c0eb"
	},
	"cython": {
		"name": "Cython",
		"color": "#fedf5b"
	},
	"d": {
		"name": "D",
		"color": "#ba595e"
	},
	"d2": {
		"name": "D2",
		"color": "#526ee8"
	},
	"d2lang": {
		"name": "D2",
		"color": "#526ee8"
	},
	"dafny": {
		"name": "Dafny",
		"color": "#FFEC25"
	},
	"darcs patch": {
		"name": "Darcs Patch",
		"color": "#8eff23"
	},
	"dart": {
		"name": "Dart",
		"color": "#00B4AB"
	},
	"daslang": {
		"name": "Daslang",
		"color": "#d3d3d3"
	},
	"dataweave": {
		"name": "DataWeave",
		"color": "#003a52"
	},
	"debian package control file": {
		"name": "Debian Package Control File",
		"color": "#D70751"
	},
	"delphi": {
		"name": "Pascal",
		"color": "#E3F171"
	},
	"denizenscript": {
		"name": "DenizenScript",
		"color": "#FBEE96"
	},
	"dhall": {
		"name": "Dhall",
		"color": "#dfafff"
	},
	"directx 3d file": {
		"name": "DirectX 3D File",
		"color": "#aace60"
	},
	"django": {
		"name": "Jinja",
		"color": "#a52a22"
	},
	"dlang": {
		"name": "D",
		"color": "#ba595e"
	},
	"dm": {
		"name": "DM",
		"color": "#447265"
	},
	"dockerfile": {
		"name": "Dockerfile",
		"color": "#384d54"
	},
	"dogescript": {
		"name": "Dogescript",
		"color": "#cca760"
	},
	"dosbatch": {
		"name": "Batchfile",
		"color": "#C1F12E"
	},
	"dosini": {
		"name": "INI",
		"color": "#d1dbe0"
	},
	"dotenv": {
		"name": "Dotenv",
		"color": "#e5d559"
	},
	"dpatch": {
		"name": "Darcs Patch",
		"color": "#8eff23"
	},
	"dune": {
		"name": "Dune",
		"color": "#89421e"
	},
	"dylan": {
		"name": "Dylan",
		"color": "#6c616e"
	},
	"e": {
		"name": "E",
		"color": "#ccce35"
	},
	"earthfile": {
		"name": "Earthly",
		"color": "#2af0ff"
	},
	"earthly": {
		"name": "Earthly",
		"color": "#2af0ff"
	},
	"eask": {
		"name": "Emacs Lisp",
		"color": "#c065db"
	},
	"easybuild": {
		"name": "Easybuild",
		"color": "#069406"
	},
	"ec": {
		"name": "eC",
		"color": "#913960"
	},
	"ecere projects": {
		"name": "Ecere Projects",
		"color": "#913960"
	},
	"ecl": {
		"name": "ECL",
		"color": "#8a1267"
	},
	"eclipse": {
		"name": "ECLiPSe",
		"color": "#001d9d"
	},
	"ecmarkdown": {
		"name": "Ecmarkup",
		"color": "#eb8131"
	},
	"ecmarkup": {
		"name": "Ecmarkup",
		"color": "#eb8131"
	},
	"ecr": {
		"name": "HTML+ECR",
		"color": "#2e1052"
	},
	"edge": {
		"name": "Edge",
		"color": "#0dffe0"
	},
	"edgeql": {
		"name": "EdgeQL",
		"color": "#31A7FF"
	},
	"editor-config": {
		"name": "EditorConfig",
		"color": "#fff1f2"
	},
	"editorconfig": {
		"name": "EditorConfig",
		"color": "#fff1f2"
	},
	"eeschema schematic": {
		"name": "KiCad Schematic",
		"color": "#2f4aab"
	},
	"eex": {
		"name": "HTML+EEX",
		"color": "#6e4a7e"
	},
	"eiffel": {
		"name": "Eiffel",
		"color": "#4d6977"
	},
	"ejs": {
		"name": "EJS",
		"color": "#a91e50"
	},
	"electronic business card": {
		"name": "vCard",
		"color": "#ee2647"
	},
	"elisp": {
		"name": "Emacs Lisp",
		"color": "#c065db"
	},
	"elixir": {
		"name": "Elixir",
		"color": "#6e4a7e"
	},
	"elm": {
		"name": "Elm",
		"color": "#60B5CC"
	},
	"elvish": {
		"name": "Elvish",
		"color": "#55BB55"
	},
	"elvish transcript": {
		"name": "Elvish Transcript",
		"color": "#55BB55"
	},
	"emacs": {
		"name": "Emacs Lisp",
		"color": "#c065db"
	},
	"emacs lisp": {
		"name": "Emacs Lisp",
		"color": "#c065db"
	},
	"emberscript": {
		"name": "EmberScript",
		"color": "#FFF4F3"
	},
	"envrc": {
		"name": "Shell",
		"color": "#89e051"
	},
	"eq": {
		"name": "EQ",
		"color": "#a78649"
	},
	"erb": {
		"name": "HTML+ERB",
		"color": "#701516"
	},
	"erlang": {
		"name": "Erlang",
		"color": "#B83998"
	},
	"esdl": {
		"name": "EdgeQL",
		"color": "#31A7FF"
	},
	"euphoria": {
		"name": "Euphoria",
		"color": "#FF790B"
	},
	"f*": {
		"name": "F*",
		"color": "#572e30"
	},
	"f#": {
		"name": "F#",
		"color": "#b845fc"
	},
	"factor": {
		"name": "Factor",
		"color": "#636746"
	},
	"fancy": {
		"name": "Fancy",
		"color": "#7b9db4"
	},
	"fantom": {
		"name": "Fantom",
		"color": "#14253c"
	},
	"faust": {
		"name": "Faust",
		"color": "#c37240"
	},
	"fb": {
		"name": "FreeBASIC",
		"color": "#141AC9"
	},
	"fennel": {
		"name": "Fennel",
		"color": "#fff3d7"
	},
	"figfont": {
		"name": "FIGlet Font",
		"color": "#FFDDBB"
	},
	"figlet font": {
		"name": "FIGlet Font",
		"color": "#FFDDBB"
	},
	"filebench wml": {
		"name": "Filebench WML",
		"color": "#F6B900"
	},
	"firrtl": {
		"name": "FIRRTL",
		"color": "#2f632f"
	},
	"fish": {
		"name": "fish",
		"color": "#4aae47"
	},
	"flatbuffers": {
		"name": "FlatBuffers",
		"color": "#ed284a"
	},
	"flex": {
		"name": "Lex",
		"color": "#DBCA00"
	},
	"flix": {
		"name": "Flix",
		"color": "#d44a45"
	},
	"fluent": {
		"name": "Fluent",
		"color": "#ffcc33"
	},
	"flux": {
		"name": "FLUX",
		"color": "#88ccff"
	},
	"forth": {
		"name": "Forth",
		"color": "#341708"
	},
	"fortran": {
		"name": "Fortran",
		"color": "#4d41b1"
	},
	"fortran free form": {
		"name": "Fortran Free Form",
		"color": "#4d41b1"
	},
	"foxpro": {
		"name": "xBase",
		"color": "#403a40"
	},
	"freebasic": {
		"name": "FreeBASIC",
		"color": "#141AC9"
	},
	"freemarker": {
		"name": "FreeMarker",
		"color": "#0050b2"
	},
	"frege": {
		"name": "Frege",
		"color": "#00cafe"
	},
	"fsharp": {
		"name": "F#",
		"color": "#b845fc"
	},
	"fstar": {
		"name": "F*",
		"color": "#572e30"
	},
	"ftl": {
		"name": "FreeMarker",
		"color": "#0050b2"
	},
	"futhark": {
		"name": "Futhark",
		"color": "#5f021f"
	},
	"g-code": {
		"name": "G-code",
		"color": "#D08CF2"
	},
	"game maker language": {
		"name": "Game Maker Language",
		"color": "#71b417"
	},
	"gaml": {
		"name": "GAML",
		"color": "#FFC766"
	},
	"gams": {
		"name": "GAMS",
		"color": "#f49a22"
	},
	"gap": {
		"name": "GAP",
		"color": "#0000cc"
	},
	"gcc machine description": {
		"name": "GCC Machine Description",
		"color": "#FFCFAB"
	},
	"gdscript": {
		"name": "GDScript",
		"color": "#355570"
	},
	"gdshader": {
		"name": "GDShader",
		"color": "#478CBF"
	},
	"gedcom": {
		"name": "GEDCOM",
		"color": "#003058"
	},
	"gemfile.lock": {
		"name": "Gemfile.lock",
		"color": "#701516"
	},
	"gemini": {
		"name": "Gemini",
		"color": "#ff6900"
	},
	"gemtext": {
		"name": "Gemini",
		"color": "#ff6900"
	},
	"genero 4gl": {
		"name": "Genero 4gl",
		"color": "#63408e"
	},
	"genero per": {
		"name": "Genero per",
		"color": "#d8df39"
	},
	"genie": {
		"name": "Genie",
		"color": "#fb855d"
	},
	"genshi": {
		"name": "Genshi",
		"color": "#951531"
	},
	"gentoo ebuild": {
		"name": "Gentoo Ebuild",
		"color": "#9400ff"
	},
	"gentoo eclass": {
		"name": "Gentoo Eclass",
		"color": "#9400ff"
	},
	"geojson": {
		"name": "JSON",
		"color": "#292929"
	},
	"gerber image": {
		"name": "Gerber Image",
		"color": "#d20b00"
	},
	"gf": {
		"name": "Grammatical Framework",
		"color": "#ff0000"
	},
	"gherkin": {
		"name": "Gherkin",
		"color": "#5B2063"
	},
	"git attributes": {
		"name": "Git Attributes",
		"color": "#F44D27"
	},
	"git blame ignore revs": {
		"name": "Git Revision List",
		"color": "#F44D27"
	},
	"git commit": {
		"name": "Git Commit",
		"color": "#F44D27"
	},
	"git config": {
		"name": "Git Config",
		"color": "#F44D27"
	},
	"git revision list": {
		"name": "Git Revision List",
		"color": "#F44D27"
	},
	"git-ignore": {
		"name": "Ignore List",
		"color": "#000000"
	},
	"gitattributes": {
		"name": "Git Attributes",
		"color": "#F44D27"
	},
	"gitconfig": {
		"name": "Git Config",
		"color": "#F44D27"
	},
	"gitignore": {
		"name": "Ignore List",
		"color": "#000000"
	},
	"gitmodules": {
		"name": "Git Config",
		"color": "#F44D27"
	},
	"gjs": {
		"name": "Glimmer JS",
		"color": "#F5835F"
	},
	"gleam": {
		"name": "Gleam",
		"color": "#ffaff3"
	},
	"glimmer js": {
		"name": "Glimmer JS",
		"color": "#F5835F"
	},
	"glimmer ts": {
		"name": "Glimmer TS",
		"color": "#3178c6"
	},
	"glsl": {
		"name": "GLSL",
		"color": "#5686a5"
	},
	"glyph": {
		"name": "Glyph",
		"color": "#c1ac7f"
	},
	"gnuplot": {
		"name": "Gnuplot",
		"color": "#f0a9f0"
	},
	"go": {
		"name": "Go",
		"color": "#00ADD8"
	},
	"go checksums": {
		"name": "Go Checksums",
		"color": "#00ADD8"
	},
	"go mod": {
		"name": "Go Module",
		"color": "#00ADD8"
	},
	"go module": {
		"name": "Go Module",
		"color": "#00ADD8"
	},
	"go sum": {
		"name": "Go Checksums",
		"color": "#00ADD8"
	},
	"go template": {
		"name": "Go Template",
		"color": "#00ADD8"
	},
	"go work": {
		"name": "Go Workspace",
		"color": "#00ADD8"
	},
	"go work sum": {
		"name": "Go Checksums",
		"color": "#00ADD8"
	},
	"go workspace": {
		"name": "Go Workspace",
		"color": "#00ADD8"
	},
	"go.mod": {
		"name": "Go Module",
		"color": "#00ADD8"
	},
	"go.sum": {
		"name": "Go Checksums",
		"color": "#00ADD8"
	},
	"go.work": {
		"name": "Go Workspace",
		"color": "#00ADD8"
	},
	"go.work.sum": {
		"name": "Go Checksums",
		"color": "#00ADD8"
	},
	"godot resource": {
		"name": "Godot Resource",
		"color": "#355570"
	},
	"golang": {
		"name": "Go",
		"color": "#00ADD8"
	},
	"golo": {
		"name": "Golo",
		"color": "#88562A"
	},
	"gosu": {
		"name": "Gosu",
		"color": "#82937f"
	},
	"gotmpl": {
		"name": "Go Template",
		"color": "#00ADD8"
	},
	"grace": {
		"name": "Grace",
		"color": "#615f8b"
	},
	"gradle": {
		"name": "Gradle",
		"color": "#02303a"
	},
	"gradle kotlin dsl": {
		"name": "Gradle Kotlin DSL",
		"color": "#02303a"
	},
	"grammatical framework": {
		"name": "Grammatical Framework",
		"color": "#ff0000"
	},
	"graphql": {
		"name": "GraphQL",
		"color": "#e10098"
	},
	"graphviz (dot)": {
		"name": "Graphviz (DOT)",
		"color": "#2596be"
	},
	"groff": {
		"name": "Roff",
		"color": "#ecdebe"
	},
	"groovy": {
		"name": "Groovy",
		"color": "#4298b8"
	},
	"groovy server pages": {
		"name": "Groovy Server Pages",
		"color": "#4298b8"
	},
	"gsc": {
		"name": "GSC",
		"color": "#FF6800"
	},
	"gsp": {
		"name": "Groovy Server Pages",
		"color": "#4298b8"
	},
	"gts": {
		"name": "Glimmer TS",
		"color": "#3178c6"
	},
	"hack": {
		"name": "Hack",
		"color": "#878787"
	},
	"haml": {
		"name": "Haml",
		"color": "#ece2a9"
	},
	"handlebars": {
		"name": "Handlebars",
		"color": "#f7931e"
	},
	"haproxy": {
		"name": "HAProxy",
		"color": "#106da9"
	},
	"harbour": {
		"name": "Harbour",
		"color": "#0e60e3"
	},
	"hare": {
		"name": "Hare",
		"color": "#9d7424"
	},
	"hashicorp configuration language": {
		"name": "HCL",
		"color": "#844FBA"
	},
	"haskell": {
		"name": "Haskell",
		"color": "#5e5086"
	},
	"haxe": {
		"name": "Haxe",
		"color": "#df7900"
	},
	"hbs": {
		"name": "Handlebars",
		"color": "#f7931e"
	},
	"hcl": {
		"name": "HCL",
		"color": "#844FBA"
	},
	"heex": {
		"name": "HTML+EEX",
		"color": "#6e4a7e"
	},
	"help": {
		"name": "Vim Help File",
		"color": "#199f4b"
	},
	"hip": {
		"name": "HIP",
		"color": "#4F3A4F"
	},
	"hiveql": {
		"name": "HiveQL",
		"color": "#dce200"
	},
	"hls playlist": {
		"name": "M3U",
		"color": "#179C7D"
	},
	"hlsl": {
		"name": "HLSL",
		"color": "#aace60"
	},
	"hocon": {
		"name": "HOCON",
		"color": "#9ff8ee"
	},
	"holyc": {
		"name": "HolyC",
		"color": "#ffefaf"
	},
	"hoon": {
		"name": "hoon",
		"color": "#00b171"
	},
	"hosts": {
		"name": "Hosts File",
		"color": "#308888"
	},
	"hosts file": {
		"name": "Hosts File",
		"color": "#308888"
	},
	"html": {
		"name": "HTML",
		"color": "#e34c26"
	},
	"html+django": {
		"name": "Jinja",
		"color": "#a52a22"
	},
	"html+ecr": {
		"name": "HTML+ECR",
		"color": "#2e1052"
	},
	"html+eex": {
		"name": "HTML+EEX",
		"color": "#6e4a7e"
	},
	"html+erb": {
		"name": "HTML+ERB",
		"color": "#701516"
	},
	"html+jinja": {
		"name": "Jinja",
		"color": "#a52a22"
	},
	"html+php": {
		"name": "HTML+PHP",
		"color": "#4f5d95"
	},
	"html+razor": {
		"name": "HTML+Razor",
		"color": "#512be4"
	},
	"html+ruby": {
		"name": "HTML+ERB",
		"color": "#701516"
	},
	"htmlbars": {
		"name": "Handlebars",
		"color": "#f7931e"
	},
	"htmldjango": {
		"name": "Jinja",
		"color": "#a52a22"
	},
	"http": {
		"name": "HTTP",
		"color": "#005C9C"
	},
	"hurl": {
		"name": "Hurl",
		"color": "#FF0288"
	},
	"hxml": {
		"name": "HXML",
		"color": "#f68712"
	},
	"hy": {
		"name": "Hy",
		"color": "#7790B2"
	},
	"hylang": {
		"name": "Hy",
		"color": "#7790B2"
	},
	"ical": {
		"name": "iCalendar",
		"color": "#ec564c"
	},
	"icalendar": {
		"name": "iCalendar",
		"color": "#ec564c"
	},
	"idl": {
		"name": "IDL",
		"color": "#a3522f"
	},
	"idris": {
		"name": "Idris",
		"color": "#b30000"
	},
	"ignore": {
		"name": "Ignore List",
		"color": "#000000"
	},
	"ignore list": {
		"name": "Ignore List",
		"color": "#000000"
	},
	"igor": {
		"name": "IGOR Pro",
		"color": "#0000cc"
	},
	"igor pro": {
		"name": "IGOR Pro",
		"color": "#0000cc"
	},
	"igorpro": {
		"name": "IGOR Pro",
		"color": "#0000cc"
	},
	"ijm": {
		"name": "ImageJ Macro",
		"color": "#99AAFF"
	},
	"il assembly": {
		"name": "IL Assembly",
		"color": "#512BD4"
	},
	"ilasm": {
		"name": "IL Assembly",
		"color": "#512BD4"
	},
	"ile rpg": {
		"name": "RPGLE",
		"color": "#2BDE21"
	},
	"imagej macro": {
		"name": "ImageJ Macro",
		"color": "#99AAFF"
	},
	"imba": {
		"name": "Imba",
		"color": "#16cec6"
	},
	"inc": {
		"name": "PHP",
		"color": "#4F5D95"
	},
	"ini": {
		"name": "INI",
		"color": "#d1dbe0"
	},
	"inno setup": {
		"name": "Inno Setup",
		"color": "#264b99"
	},
	"io": {
		"name": "Io",
		"color": "#a9188d"
	},
	"ioke": {
		"name": "Ioke",
		"color": "#078193"
	},
	"ipython notebook": {
		"name": "Jupyter Notebook",
		"color": "#DA5B0B"
	},
	"isabelle": {
		"name": "Isabelle",
		"color": "#FEFE00"
	},
	"isabelle root": {
		"name": "Isabelle ROOT",
		"color": "#FEFE00"
	},
	"ispc": {
		"name": "ISPC",
		"color": "#2D68B1"
	},
	"j": {
		"name": "J",
		"color": "#9EEDFF"
	},
	"jac": {
		"name": "Jac",
		"color": "#FC792D"
	},
	"jai": {
		"name": "Jai",
		"color": "#ab8b4b"
	},
	"janet": {
		"name": "Janet",
		"color": "#0886a5"
	},
	"jar manifest": {
		"name": "JAR Manifest",
		"color": "#b07219"
	},
	"jasmin": {
		"name": "Jasmin",
		"color": "#d03600"
	},
	"java": {
		"name": "Java",
		"color": "#b07219"
	},
	"java properties": {
		"name": "Java Properties",
		"color": "#2A6277"
	},
	"java server page": {
		"name": "Groovy Server Pages",
		"color": "#4298b8"
	},
	"java server pages": {
		"name": "Java Server Pages",
		"color": "#2A6277"
	},
	"java template engine": {
		"name": "Java Template Engine",
		"color": "#2A6277"
	},
	"javascript": {
		"name": "JavaScript",
		"color": "#f1e05a"
	},
	"javascript+erb": {
		"name": "JavaScript+ERB",
		"color": "#f1e05a"
	},
	"jcl": {
		"name": "JCL",
		"color": "#d90e09"
	},
	"jest snapshot": {
		"name": "Jest Snapshot",
		"color": "#15c213"
	},
	"jetbrains mps": {
		"name": "JetBrains MPS",
		"color": "#21D789"
	},
	"jflex": {
		"name": "JFlex",
		"color": "#DBCA00"
	},
	"jinja": {
		"name": "Jinja",
		"color": "#a52a22"
	},
	"jison": {
		"name": "Jison",
		"color": "#56b3cb"
	},
	"jison lex": {
		"name": "Jison Lex",
		"color": "#56b3cb"
	},
	"jolie": {
		"name": "Jolie",
		"color": "#843179"
	},
	"jq": {
		"name": "jq",
		"color": "#c7254e"
	},
	"jruby": {
		"name": "Ruby",
		"color": "#701516"
	},
	"js": {
		"name": "JavaScript",
		"color": "#f1e05a"
	},
	"json": {
		"name": "JSON",
		"color": "#292929"
	},
	"json with comments": {
		"name": "JSON with Comments",
		"color": "#292929"
	},
	"json5": {
		"name": "JSON5",
		"color": "#267CB9"
	},
	"jsonc": {
		"name": "JSON with Comments",
		"color": "#292929"
	},
	"jsoniq": {
		"name": "JSONiq",
		"color": "#40d47e"
	},
	"jsonl": {
		"name": "JSON",
		"color": "#292929"
	},
	"jsonld": {
		"name": "JSONLD",
		"color": "#0c479c"
	},
	"jsonnet": {
		"name": "Jsonnet",
		"color": "#0064bd"
	},
	"jsp": {
		"name": "Java Server Pages",
		"color": "#2A6277"
	},
	"jte": {
		"name": "Java Template Engine",
		"color": "#2A6277"
	},
	"julia": {
		"name": "Julia",
		"color": "#a270ba"
	},
	"julia repl": {
		"name": "Julia REPL",
		"color": "#a270ba"
	},
	"jupyter notebook": {
		"name": "Jupyter Notebook",
		"color": "#DA5B0B"
	},
	"just": {
		"name": "Just",
		"color": "#384d54"
	},
	"justfile": {
		"name": "Just",
		"color": "#384d54"
	},
	"kaitai struct": {
		"name": "Kaitai Struct",
		"color": "#773b37"
	},
	"kak": {
		"name": "KakouneScript",
		"color": "#6f8042"
	},
	"kakounescript": {
		"name": "KakouneScript",
		"color": "#6f8042"
	},
	"kakscript": {
		"name": "KakouneScript",
		"color": "#6f8042"
	},
	"kcl": {
		"name": "KCL",
		"color": "#7ABABF"
	},
	"kdl": {
		"name": "KDL",
		"color": "#ffb3b3"
	},
	"kerboscript": {
		"name": "KerboScript",
		"color": "#41adf0"
	},
	"keyvalues": {
		"name": "Valve Data Format",
		"color": "#f26025"
	},
	"kframework": {
		"name": "KFramework",
		"color": "#4195c5"
	},
	"kicad layout": {
		"name": "KiCad Layout",
		"color": "#2f4aab"
	},
	"kicad legacy layout": {
		"name": "KiCad Legacy Layout",
		"color": "#2f4aab"
	},
	"kicad schematic": {
		"name": "KiCad Schematic",
		"color": "#2f4aab"
	},
	"koka": {
		"name": "Koka",
		"color": "#215166"
	},
	"kolmafia ash": {
		"name": "KoLmafia ASH",
		"color": "#B9D9B9"
	},
	"kotlin": {
		"name": "Kotlin",
		"color": "#A97BFF"
	},
	"krl": {
		"name": "KRL",
		"color": "#28430A"
	},
	"ksy": {
		"name": "Kaitai Struct",
		"color": "#773b37"
	},
	"kvlang": {
		"name": "kvlang",
		"color": "#1da6e0"
	},
	"labview": {
		"name": "LabVIEW",
		"color": "#fede06"
	},
	"lambdapi": {
		"name": "Lambdapi",
		"color": "#8027a3"
	},
	"langium": {
		"name": "Langium",
		"color": "#2c8c87"
	},
	"lark": {
		"name": "Lark",
		"color": "#2980B9"
	},
	"lasso": {
		"name": "Lasso",
		"color": "#999999"
	},
	"lassoscript": {
		"name": "Lasso",
		"color": "#999999"
	},
	"latex": {
		"name": "TeX",
		"color": "#3D6117"
	},
	"latte": {
		"name": "Latte",
		"color": "#f2a542"
	},
	"leex": {
		"name": "HTML+EEX",
		"color": "#6e4a7e"
	},
	"leo": {
		"name": "Leo",
		"color": "#C4FFC2"
	},
	"less": {
		"name": "Less",
		"color": "#1d365d"
	},
	"less-css": {
		"name": "Less",
		"color": "#1d365d"
	},
	"lex": {
		"name": "Lex",
		"color": "#DBCA00"
	},
	"lfe": {
		"name": "LFE",
		"color": "#4C3023"
	},
	"lhaskell": {
		"name": "Literate Haskell",
		"color": "#5e5086"
	},
	"lhs": {
		"name": "Literate Haskell",
		"color": "#5e5086"
	},
	"ligolang": {
		"name": "LigoLANG",
		"color": "#0e74ff"
	},
	"lilypond": {
		"name": "LilyPond",
		"color": "#9ccc7c"
	},
	"liquid": {
		"name": "Liquid",
		"color": "#67b8de"
	},
	"liquidsoap": {
		"name": "Liquidsoap",
		"color": "#990066"
	},
	"lisp": {
		"name": "Common Lisp",
		"color": "#3fb68b"
	},
	"litcoffee": {
		"name": "Literate CoffeeScript",
		"color": "#244776"
	},
	"literate agda": {
		"name": "Literate Agda",
		"color": "#315665"
	},
	"literate coffeescript": {
		"name": "Literate CoffeeScript",
		"color": "#244776"
	},
	"literate haskell": {
		"name": "Literate Haskell",
		"color": "#5e5086"
	},
	"live-script": {
		"name": "LiveScript",
		"color": "#499886"
	},
	"livecode script": {
		"name": "LiveCode Script",
		"color": "#0c5ba5"
	},
	"livescript": {
		"name": "LiveScript",
		"color": "#499886"
	},
	"llvm": {
		"name": "LLVM",
		"color": "#185619"
	},
	"logtalk": {
		"name": "Logtalk",
		"color": "#295b9a"
	},
	"lolcode": {
		"name": "LOLCODE",
		"color": "#cc9900"
	},
	"lookml": {
		"name": "LookML",
		"color": "#652B81"
	},
	"ls": {
		"name": "LiveScript",
		"color": "#499886"
	},
	"lsl": {
		"name": "LSL",
		"color": "#3d9970"
	},
	"lua": {
		"name": "Lua",
		"color": "#000080"
	},
	"luau": {
		"name": "Luau",
		"color": "#00A2FF"
	},
	"m2": {
		"name": "Macaulay2",
		"color": "#d8ffff"
	},
	"m3u": {
		"name": "M3U",
		"color": "#179C7D"
	},
	"m3u playlist": {
		"name": "M3U",
		"color": "#179C7D"
	},
	"m68k": {
		"name": "Motorola 68K Assembly",
		"color": "#005daa"
	},
	"macaulay2": {
		"name": "Macaulay2",
		"color": "#d8ffff"
	},
	"macruby": {
		"name": "Ruby",
		"color": "#701516"
	},
	"make": {
		"name": "Makefile",
		"color": "#427819"
	},
	"makefile": {
		"name": "Makefile",
		"color": "#427819"
	},
	"mako": {
		"name": "Mako",
		"color": "#7e858d"
	},
	"man": {
		"name": "Roff",
		"color": "#ecdebe"
	},
	"man page": {
		"name": "Roff",
		"color": "#ecdebe"
	},
	"man-page": {
		"name": "Roff",
		"color": "#ecdebe"
	},
	"manpage": {
		"name": "Roff",
		"color": "#ecdebe"
	},
	"markdown": {
		"name": "Markdown",
		"color": "#083fa1"
	},
	"marko": {
		"name": "Marko",
		"color": "#42bff2"
	},
	"markojs": {
		"name": "Marko",
		"color": "#42bff2"
	},
	"mask": {
		"name": "Mask",
		"color": "#f97732"
	},
	"mathematica": {
		"name": "Wolfram Language",
		"color": "#dd1100"
	},
	"mathematical programming system": {
		"name": "Mathematical Programming System",
		"color": "#0530ad"
	},
	"matlab": {
		"name": "MATLAB",
		"color": "#e16737"
	},
	"max": {
		"name": "Max",
		"color": "#c4a79c"
	},
	"max/msp": {
		"name": "Max",
		"color": "#c4a79c"
	},
	"maxmsp": {
		"name": "Max",
		"color": "#c4a79c"
	},
	"maxscript": {
		"name": "MAXScript",
		"color": "#00a6a6"
	},
	"mcfunction": {
		"name": "mcfunction",
		"color": "#E22837"
	},
	"md": {
		"name": "Markdown",
		"color": "#083fa1"
	},
	"mdoc": {
		"name": "Roff",
		"color": "#ecdebe"
	},
	"mdsvex": {
		"name": "mdsvex",
		"color": "#5f9ea0"
	},
	"mdx": {
		"name": "MDX",
		"color": "#fcb32c"
	},
	"mediawiki": {
		"name": "Wikitext",
		"color": "#fc5757"
	},
	"mercury": {
		"name": "Mercury",
		"color": "#ff2b2b"
	},
	"mermaid": {
		"name": "Mermaid",
		"color": "#ff3670"
	},
	"mermaid example": {
		"name": "Mermaid",
		"color": "#ff3670"
	},
	"meson": {
		"name": "Meson",
		"color": "#007800"
	},
	"metal": {
		"name": "Metal",
		"color": "#8f14e9"
	},
	"metta": {
		"name": "MeTTa",
		"color": "#6a5acd"
	},
	"mf": {
		"name": "Makefile",
		"color": "#427819"
	},
	"miniyaml": {
		"name": "MiniYAML",
		"color": "#ff1111"
	},
	"minizinc": {
		"name": "MiniZinc",
		"color": "#06a9e6"
	},
	"mint": {
		"name": "Mint",
		"color": "#02b046"
	},
	"mirah": {
		"name": "Mirah",
		"color": "#c7a938"
	},
	"mirc script": {
		"name": "mIRC Script",
		"color": "#3d57c3"
	},
	"mlir": {
		"name": "MLIR",
		"color": "#5EC8DB"
	},
	"mma": {
		"name": "Wolfram Language",
		"color": "#dd1100"
	},
	"modelica": {
		"name": "Modelica",
		"color": "#de1d31"
	},
	"modula-2": {
		"name": "Modula-2",
		"color": "#10253f"
	},
	"modula-3": {
		"name": "Modula-3",
		"color": "#223388"
	},
	"mojo": {
		"name": "Mojo",
		"color": "#ff4c1f"
	},
	"monkey c": {
		"name": "Monkey C",
		"color": "#8D6747"
	},
	"moonbit": {
		"name": "MoonBit",
		"color": "#b92381"
	},
	"moonscript": {
		"name": "MoonScript",
		"color": "#ff4585"
	},
	"motoko": {
		"name": "Motoko",
		"color": "#fbb03b"
	},
	"motorola 68k assembly": {
		"name": "Motorola 68K Assembly",
		"color": "#005daa"
	},
	"move": {
		"name": "Move",
		"color": "#4a137a"
	},
	"mps": {
		"name": "JetBrains MPS",
		"color": "#21D789"
	},
	"mql4": {
		"name": "MQL4",
		"color": "#62A8D6"
	},
	"mql5": {
		"name": "MQL5",
		"color": "#4A76B8"
	},
	"msil": {
		"name": "IL Assembly",
		"color": "#512BD4"
	},
	"mtml": {
		"name": "MTML",
		"color": "#b7e1f4"
	},
	"mupad": {
		"name": "mupad",
		"color": "#244963"
	},
	"mustache": {
		"name": "Mustache",
		"color": "#724b3b"
	},
	"nanorc": {
		"name": "nanorc",
		"color": "#2d004d"
	},
	"nargo": {
		"name": "Noir",
		"color": "#2f1f49"
	},
	"nasal": {
		"name": "Nasal",
		"color": "#1d2c4e"
	},
	"nasm": {
		"name": "Assembly",
		"color": "#6E4C13"
	},
	"ncl": {
		"name": "NCL",
		"color": "#28431f"
	},
	"nearley": {
		"name": "Nearley",
		"color": "#990000"
	},
	"nemerle": {
		"name": "Nemerle",
		"color": "#3d3c6e"
	},
	"neosnippet": {
		"name": "Vim Snippet",
		"color": "#199f4b"
	},
	"nesc": {
		"name": "nesC",
		"color": "#94B0C7"
	},
	"netlinx": {
		"name": "NetLinx",
		"color": "#0aa0ff"
	},
	"netlinx+erb": {
		"name": "NetLinx+ERB",
		"color": "#747faa"
	},
	"netlogo": {
		"name": "NetLogo",
		"color": "#ff6375"
	},
	"newlisp": {
		"name": "NewLisp",
		"color": "#87AED7"
	},
	"nextflow": {
		"name": "Nextflow",
		"color": "#3ac486"
	},
	"nginx": {
		"name": "Nginx",
		"color": "#009639"
	},
	"nginx configuration file": {
		"name": "Nginx",
		"color": "#009639"
	},
	"nickel": {
		"name": "Nickel",
		"color": "#E0C3FC"
	},
	"nim": {
		"name": "Nim",
		"color": "#ffc200"
	},
	"nit": {
		"name": "Nit",
		"color": "#009917"
	},
	"nix": {
		"name": "Nix",
		"color": "#7e7eff"
	},
	"nixos": {
		"name": "Nix",
		"color": "#7e7eff"
	},
	"njk": {
		"name": "Nunjucks",
		"color": "#3d8137"
	},
	"nmodl": {
		"name": "NMODL",
		"color": "#00356B"
	},
	"node": {
		"name": "JavaScript",
		"color": "#f1e05a"
	},
	"noir": {
		"name": "Noir",
		"color": "#2f1f49"
	},
	"npm config": {
		"name": "NPM Config",
		"color": "#cb3837"
	},
	"npmrc": {
		"name": "NPM Config",
		"color": "#cb3837"
	},
	"nroff": {
		"name": "Roff",
		"color": "#ecdebe"
	},
	"nu": {
		"name": "Nu",
		"color": "#c9df40"
	},
	"nu-script": {
		"name": "Nushell",
		"color": "#4E9906"
	},
	"numpy": {
		"name": "NumPy",
		"color": "#9C8AF9"
	},
	"nunjucks": {
		"name": "Nunjucks",
		"color": "#3d8137"
	},
	"nush": {
		"name": "Nu",
		"color": "#c9df40"
	},
	"nushell": {
		"name": "Nushell",
		"color": "#4E9906"
	},
	"nushell-script": {
		"name": "Nushell",
		"color": "#4E9906"
	},
	"nvim": {
		"name": "Vim Script",
		"color": "#199f4b"
	},
	"nwscript": {
		"name": "NWScript",
		"color": "#111522"
	},
	"oasv2": {
		"name": "OpenAPI Specification v2",
		"color": "#85ea2d"
	},
	"oasv2-json": {
		"name": "OASv2-json",
		"color": "#85ea2d"
	},
	"oasv2-yaml": {
		"name": "OASv2-yaml",
		"color": "#85ea2d"
	},
	"oasv3": {
		"name": "OpenAPI Specification v3",
		"color": "#85ea2d"
	},
	"oasv3-json": {
		"name": "OASv3-json",
		"color": "#85ea2d"
	},
	"oasv3-yaml": {
		"name": "OASv3-yaml",
		"color": "#85ea2d"
	},
	"obj-c": {
		"name": "Objective-C",
		"color": "#438eff"
	},
	"obj-c++": {
		"name": "Objective-C++",
		"color": "#6866fb"
	},
	"obj-j": {
		"name": "Objective-J",
		"color": "#ff0c5a"
	},
	"objc": {
		"name": "Objective-C",
		"color": "#438eff"
	},
	"objc++": {
		"name": "Objective-C++",
		"color": "#6866fb"
	},
	"objective-c": {
		"name": "Objective-C",
		"color": "#438eff"
	},
	"objective-c++": {
		"name": "Objective-C++",
		"color": "#6866fb"
	},
	"objective-j": {
		"name": "Objective-J",
		"color": "#ff0c5a"
	},
	"objectivec": {
		"name": "Objective-C",
		"color": "#438eff"
	},
	"objectivec++": {
		"name": "Objective-C++",
		"color": "#6866fb"
	},
	"objectivej": {
		"name": "Objective-J",
		"color": "#ff0c5a"
	},
	"objectpascal": {
		"name": "Pascal",
		"color": "#E3F171"
	},
	"objectscript": {
		"name": "ObjectScript",
		"color": "#424893"
	},
	"objj": {
		"name": "Objective-J",
		"color": "#ff0c5a"
	},
	"ocaml": {
		"name": "OCaml",
		"color": "#ef7a08"
	},
	"octave": {
		"name": "MATLAB",
		"color": "#e16737"
	},
	"odin": {
		"name": "Odin",
		"color": "#60AFFE"
	},
	"odin-lang": {
		"name": "Odin",
		"color": "#60AFFE"
	},
	"odinlang": {
		"name": "Odin",
		"color": "#60AFFE"
	},
	"omgrofl": {
		"name": "Omgrofl",
		"color": "#cabbff"
	},
	"omnet++ msg": {
		"name": "OMNeT++ MSG",
		"color": "#a0e0a0"
	},
	"omnet++ ned": {
		"name": "OMNeT++ NED",
		"color": "#08607c"
	},
	"omnetpp-msg": {
		"name": "OMNeT++ MSG",
		"color": "#a0e0a0"
	},
	"omnetpp-ned": {
		"name": "OMNeT++ NED",
		"color": "#08607c"
	},
	"ooc": {
		"name": "ooc",
		"color": "#b0b77e"
	},
	"opal": {
		"name": "Opal",
		"color": "#f7ede0"
	},
	"open policy agent": {
		"name": "Open Policy Agent",
		"color": "#7d9199"
	},
	"openapi specification v2": {
		"name": "OpenAPI Specification v2",
		"color": "#85ea2d"
	},
	"openapi specification v3": {
		"name": "OpenAPI Specification v3",
		"color": "#85ea2d"
	},
	"opencl": {
		"name": "OpenCL",
		"color": "#ed2e2d"
	},
	"openedge": {
		"name": "OpenEdge ABL",
		"color": "#5ce600"
	},
	"openedge abl": {
		"name": "OpenEdge ABL",
		"color": "#5ce600"
	},
	"openqasm": {
		"name": "OpenQASM",
		"color": "#AA70FF"
	},
	"openscad": {
		"name": "OpenSCAD",
		"color": "#e5cd45"
	},
	"opentofu": {
		"name": "HCL",
		"color": "#844FBA"
	},
	"option list": {
		"name": "Option List",
		"color": "#476732"
	},
	"opts": {
		"name": "Option List",
		"color": "#476732"
	},
	"opy": {
		"name": "OverPy",
		"color": "#78b355"
	},
	"org": {
		"name": "Org",
		"color": "#77aa99"
	},
	"osascript": {
		"name": "AppleScript",
		"color": "#101F1F"
	},
	"overpassql": {
		"name": "OverpassQL",
		"color": "#cce2aa"
	},
	"overpy": {
		"name": "OverPy",
		"color": "#78b355"
	},
	"oxygene": {
		"name": "Oxygene",
		"color": "#cdd0e3"
	},
	"oz": {
		"name": "Oz",
		"color": "#fab738"
	},
	"p4": {
		"name": "P4",
		"color": "#7055b5"
	},
	"pact": {
		"name": "Pact",
		"color": "#F7A8B8"
	},
	"pan": {
		"name": "Pan",
		"color": "#cc0000"
	},
	"pandoc": {
		"name": "Markdown",
		"color": "#083fa1"
	},
	"papyrus": {
		"name": "Papyrus",
		"color": "#6600cc"
	},
	"parrot": {
		"name": "Parrot",
		"color": "#f3ca0a"
	},
	"pascal": {
		"name": "Pascal",
		"color": "#E3F171"
	},
	"pawn": {
		"name": "Pawn",
		"color": "#dbb284"
	},
	"pcbnew": {
		"name": "KiCad Layout",
		"color": "#2f4aab"
	},
	"pddl": {
		"name": "PDDL",
		"color": "#0d00ff"
	},
	"peg.js": {
		"name": "PEG.js",
		"color": "#234d6b"
	},
	"pep8": {
		"name": "Pep8",
		"color": "#C76F5B"
	},
	"perl": {
		"name": "Perl",
		"color": "#0298c3"
	},
	"perl-6": {
		"name": "Raku",
		"color": "#0000fb"
	},
	"perl6": {
		"name": "Raku",
		"color": "#0000fb"
	},
	"php": {
		"name": "PHP",
		"color": "#4F5D95"
	},
	"picolisp": {
		"name": "PicoLisp",
		"color": "#6067af"
	},
	"piglatin": {
		"name": "PigLatin",
		"color": "#fcd7de"
	},
	"pike": {
		"name": "Pike",
		"color": "#005390"
	},
	"pip requirements": {
		"name": "Pip Requirements",
		"color": "#FFD343"
	},
	"pkg-config": {
		"name": "pkg-config",
		"color": "#2b5e82"
	},
	"pkgconf": {
		"name": "pkg-config",
		"color": "#2b5e82"
	},
	"pkl": {
		"name": "Pkl",
		"color": "#6b9543"
	},
	"plantuml": {
		"name": "PlantUML",
		"color": "#fbbd16"
	},
	"plpgsql": {
		"name": "PLpgSQL",
		"color": "#336790"
	},
	"plsql": {
		"name": "PLSQL",
		"color": "#dad8d8"
	},
	"pogoscript": {
		"name": "PogoScript",
		"color": "#d80074"
	},
	"polar": {
		"name": "Polar",
		"color": "#ae81ff"
	},
	"portugol": {
		"name": "Portugol",
		"color": "#f8bd00"
	},
	"posh": {
		"name": "PowerShell",
		"color": "#012456"
	},
	"postcss": {
		"name": "PostCSS",
		"color": "#dc3a0c"
	},
	"postscr": {
		"name": "PostScript",
		"color": "#da291c"
	},
	"postscript": {
		"name": "PostScript",
		"color": "#da291c"
	},
	"pov-ray": {
		"name": "POV-Ray SDL",
		"color": "#6bac65"
	},
	"pov-ray sdl": {
		"name": "POV-Ray SDL",
		"color": "#6bac65"
	},
	"povray": {
		"name": "POV-Ray SDL",
		"color": "#6bac65"
	},
	"powerbuilder": {
		"name": "PowerBuilder",
		"color": "#8f0f8d"
	},
	"powershell": {
		"name": "PowerShell",
		"color": "#012456"
	},
	"praat": {
		"name": "Praat",
		"color": "#c8506d"
	},
	"prisma": {
		"name": "Prisma",
		"color": "#0c344b"
	},
	"pro*c": {
		"name": "Pro*C",
		"color": "#bb8368"
	},
	"processing": {
		"name": "Processing",
		"color": "#0096D8"
	},
	"procfile": {
		"name": "Procfile",
		"color": "#3B2F63"
	},
	"progress": {
		"name": "OpenEdge ABL",
		"color": "#5ce600"
	},
	"prolog": {
		"name": "Prolog",
		"color": "#74283c"
	},
	"promela": {
		"name": "Promela",
		"color": "#de0000"
	},
	"propeller spin": {
		"name": "Propeller Spin",
		"color": "#7fa2a7"
	},
	"pug": {
		"name": "Pug",
		"color": "#a86454"
	},
	"puppet": {
		"name": "Puppet",
		"color": "#302B6D"
	},
	"purebasic": {
		"name": "PureBasic",
		"color": "#5a6986"
	},
	"purescript": {
		"name": "PureScript",
		"color": "#1D222D"
	},
	"pwsh": {
		"name": "PowerShell",
		"color": "#012456"
	},
	"py": {
		"name": "Python",
		"color": "#3572A5"
	},
	"py3": {
		"name": "Python",
		"color": "#3572A5"
	},
	"pycon": {
		"name": "Python console",
		"color": "#3572A5"
	},
	"pyret": {
		"name": "Pyret",
		"color": "#ee1e10"
	},
	"pyrex": {
		"name": "Cython",
		"color": "#fedf5b"
	},
	"python": {
		"name": "Python",
		"color": "#3572A5"
	},
	"python console": {
		"name": "Python console",
		"color": "#3572A5"
	},
	"python traceback": {
		"name": "Python traceback",
		"color": "#3572A5"
	},
	"python3": {
		"name": "Python",
		"color": "#3572A5"
	},
	"q": {
		"name": "q",
		"color": "#0040cd"
	},
	"q#": {
		"name": "Q#",
		"color": "#fed659"
	},
	"qb": {
		"name": "QuickBASIC",
		"color": "#008080"
	},
	"qb64": {
		"name": "QuickBASIC",
		"color": "#008080"
	},
	"qbasic": {
		"name": "QuickBASIC",
		"color": "#008080"
	},
	"ql": {
		"name": "CodeQL",
		"color": "#140f46"
	},
	"qml": {
		"name": "QML",
		"color": "#44a51c"
	},
	"qsharp": {
		"name": "Q#",
		"color": "#fed659"
	},
	"qt script": {
		"name": "Qt Script",
		"color": "#00b841"
	},
	"quake": {
		"name": "Quake",
		"color": "#882233"
	},
	"quakec": {
		"name": "QuakeC",
		"color": "#975777"
	},
	"quickbasic": {
		"name": "QuickBASIC",
		"color": "#008080"
	},
	"quint": {
		"name": "Quint",
		"color": "#9d6ce5"
	},
	"r": {
		"name": "R",
		"color": "#198CE7"
	},
	"racket": {
		"name": "Racket",
		"color": "#3c5caa"
	},
	"ragel": {
		"name": "Ragel",
		"color": "#9d5200"
	},
	"ragel-rb": {
		"name": "Ragel",
		"color": "#9d5200"
	},
	"ragel-ruby": {
		"name": "Ragel",
		"color": "#9d5200"
	},
	"rake": {
		"name": "Ruby",
		"color": "#701516"
	},
	"raku": {
		"name": "Raku",
		"color": "#0000fb"
	},
	"raml": {
		"name": "RAML",
		"color": "#77d9fb"
	},
	"rascal": {
		"name": "Rascal",
		"color": "#fffaa0"
	},
	"rascript": {
		"name": "RAScript",
		"color": "#2C97FA"
	},
	"razor": {
		"name": "HTML+Razor",
		"color": "#512be4"
	},
	"rb": {
		"name": "Ruby",
		"color": "#701516"
	},
	"rbs": {
		"name": "RBS",
		"color": "#701516"
	},
	"rbx": {
		"name": "Ruby",
		"color": "#701516"
	},
	"rdoc": {
		"name": "RDoc",
		"color": "#701516"
	},
	"reason": {
		"name": "Reason",
		"color": "#ff5847"
	},
	"reasonligo": {
		"name": "ReasonLIGO",
		"color": "#ff5847"
	},
	"rebol": {
		"name": "Rebol",
		"color": "#358a5b"
	},
	"record jar": {
		"name": "Record Jar",
		"color": "#0673ba"
	},
	"red": {
		"name": "Red",
		"color": "#f50000"
	},
	"red/system": {
		"name": "Red",
		"color": "#f50000"
	},
	"redscript": {
		"name": "Redscript",
		"color": "#f44336"
	},
	"regex": {
		"name": "Regular Expression",
		"color": "#009a00"
	},
	"regexp": {
		"name": "Regular Expression",
		"color": "#009a00"
	},
	"regular expression": {
		"name": "Regular Expression",
		"color": "#009a00"
	},
	"ren'py": {
		"name": "Ren'Py",
		"color": "#ff7f7f"
	},
	"renpy": {
		"name": "Ren'Py",
		"color": "#ff7f7f"
	},
	"rescript": {
		"name": "ReScript",
		"color": "#ed5051"
	},
	"restructuredtext": {
		"name": "reStructuredText",
		"color": "#141414"
	},
	"rexx": {
		"name": "REXX",
		"color": "#d90e09"
	},
	"rez": {
		"name": "Rez",
		"color": "#FFDAB3"
	},
	"rhtml": {
		"name": "HTML+ERB",
		"color": "#701516"
	},
	"ring": {
		"name": "Ring",
		"color": "#2D54CB"
	},
	"riot": {
		"name": "Riot",
		"color": "#A71E49"
	},
	"rmarkdown": {
		"name": "RMarkdown",
		"color": "#198ce7"
	},
	"robotframework": {
		"name": "RobotFramework",
		"color": "#00c0b5"
	},
	"roc": {
		"name": "Roc",
		"color": "#7c38f5"
	},
	"rocq": {
		"name": "Rocq Prover",
		"color": "#d0b68c"
	},
	"rocq prover": {
		"name": "Rocq Prover",
		"color": "#d0b68c"
	},
	"roff": {
		"name": "Roff",
		"color": "#ecdebe"
	},
	"roff manpage": {
		"name": "Roff Manpage",
		"color": "#ecdebe"
	},
	"ron": {
		"name": "RON",
		"color": "#a62c00"
	},
	"ros interface": {
		"name": "ROS Interface",
		"color": "#22314e"
	},
	"rosmsg": {
		"name": "ROS Interface",
		"color": "#22314e"
	},
	"rouge": {
		"name": "Rouge",
		"color": "#cc0088"
	},
	"routeros script": {
		"name": "RouterOS Script",
		"color": "#DE3941"
	},
	"rpgle": {
		"name": "RPGLE",
		"color": "#2BDE21"
	},
	"rs": {
		"name": "Rust",
		"color": "#dea584"
	},
	"rs-274x": {
		"name": "Gerber Image",
		"color": "#d20b00"
	},
	"rscript": {
		"name": "R",
		"color": "#198CE7"
	},
	"rss": {
		"name": "XML",
		"color": "#0060ac"
	},
	"rst": {
		"name": "reStructuredText",
		"color": "#141414"
	},
	"ruby": {
		"name": "Ruby",
		"color": "#701516"
	},
	"runoff": {
		"name": "RUNOFF",
		"color": "#665a4e"
	},
	"rust": {
		"name": "Rust",
		"color": "#dea584"
	},
	"rusthon": {
		"name": "Python",
		"color": "#3572A5"
	},
	"sail": {
		"name": "Sail",
		"color": "#259dd5"
	},
	"salt": {
		"name": "SaltStack",
		"color": "#646464"
	},
	"saltstack": {
		"name": "SaltStack",
		"color": "#646464"
	},
	"saltstate": {
		"name": "SaltStack",
		"color": "#646464"
	},
	"sarif": {
		"name": "JSON",
		"color": "#292929"
	},
	"sas": {
		"name": "SAS",
		"color": "#B34936"
	},
	"sass": {
		"name": "Sass",
		"color": "#a53b70"
	},
	"scala": {
		"name": "Scala",
		"color": "#c22d40"
	},
	"scaml": {
		"name": "Scaml",
		"color": "#bd181a"
	},
	"scenic": {
		"name": "Scenic",
		"color": "#fdc700"
	},
	"scheme": {
		"name": "Scheme",
		"color": "#1e4aec"
	},
	"scilab": {
		"name": "Scilab",
		"color": "#ca0f21"
	},
	"scss": {
		"name": "SCSS",
		"color": "#c6538c"
	},
	"sdc": {
		"name": "Tcl",
		"color": "#e4cc98"
	},
	"sed": {
		"name": "sed",
		"color": "#64b970"
	},
	"self": {
		"name": "Self",
		"color": "#0579aa"
	},
	"sfv": {
		"name": "Simple File Verification",
		"color": "#C9BFED"
	},
	"sh": {
		"name": "Shell",
		"color": "#89e051"
	},
	"shaderlab": {
		"name": "ShaderLab",
		"color": "#222c37"
	},
	"shell": {
		"name": "Shell",
		"color": "#89e051"
	},
	"shell-script": {
		"name": "Shell",
		"color": "#89e051"
	},
	"shellcheck config": {
		"name": "ShellCheck Config",
		"color": "#cecfcb"
	},
	"shellcheckrc": {
		"name": "ShellCheck Config",
		"color": "#cecfcb"
	},
	"shen": {
		"name": "Shen",
		"color": "#120F14"
	},
	"simple file verification": {
		"name": "Simple File Verification",
		"color": "#C9BFED"
	},
	"singularity": {
		"name": "Singularity",
		"color": "#64E6AD"
	},
	"slang": {
		"name": "Slang",
		"color": "#1fbec9"
	},
	"slash": {
		"name": "Slash",
		"color": "#007eff"
	},
	"slice": {
		"name": "Slice",
		"color": "#003fa2"
	},
	"slim": {
		"name": "Slim",
		"color": "#2b2b2b"
	},
	"slint": {
		"name": "Slint",
		"color": "#2379F4"
	},
	"smalltalk": {
		"name": "Smalltalk",
		"color": "#596706"
	},
	"smarty": {
		"name": "Smarty",
		"color": "#f0c040"
	},
	"smithy": {
		"name": "Smithy",
		"color": "#c44536"
	},
	"sml": {
		"name": "Standard ML",
		"color": "#dc566d"
	},
	"smpl": {
		"name": "SmPL",
		"color": "#c94949"
	},
	"snakefile": {
		"name": "Snakemake",
		"color": "#419179"
	},
	"snakemake": {
		"name": "Snakemake",
		"color": "#419179"
	},
	"snipmate": {
		"name": "Vim Snippet",
		"color": "#199f4b"
	},
	"snippet": {
		"name": "YASnippet",
		"color": "#32AB90"
	},
	"solidity": {
		"name": "Solidity",
		"color": "#AA6746"
	},
	"sourcemod": {
		"name": "SourcePawn",
		"color": "#f69e1d"
	},
	"sourcepawn": {
		"name": "SourcePawn",
		"color": "#f69e1d"
	},
	"soy": {
		"name": "Closure Templates",
		"color": "#0d948f"
	},
	"sparql": {
		"name": "SPARQL",
		"color": "#0C4597"
	},
	"spicedb schema": {
		"name": "SpiceDB Schema",
		"color": "#a5318a"
	},
	"splus": {
		"name": "R",
		"color": "#198CE7"
	},
	"sqf": {
		"name": "SQF",
		"color": "#3F3F3F"
	},
	"sql": {
		"name": "SQL",
		"color": "#e38c00"
	},
	"sqlpl": {
		"name": "SQLPL",
		"color": "#e38c00"
	},
	"sqlrpgle": {
		"name": "RPGLE",
		"color": "#2BDE21"
	},
	"squeak": {
		"name": "Smalltalk",
		"color": "#596706"
	},
	"squirrel": {
		"name": "Squirrel",
		"color": "#800000"
	},
	"srecode template": {
		"name": "SRecode Template",
		"color": "#348a34"
	},
	"stan": {
		"name": "Stan",
		"color": "#b2011d"
	},
	"standard ml": {
		"name": "Standard ML",
		"color": "#dc566d"
	},
	"starlark": {
		"name": "Starlark",
		"color": "#76d275"
	},
	"stata": {
		"name": "Stata",
		"color": "#1a5f91"
	},
	"stl": {
		"name": "STL",
		"color": "#373b5e"
	},
	"stla": {
		"name": "STL",
		"color": "#373b5e"
	},
	"stringtemplate": {
		"name": "StringTemplate",
		"color": "#3fb34f"
	},
	"stylus": {
		"name": "Stylus",
		"color": "#ff6347"
	},
	"subrip text": {
		"name": "SubRip Text",
		"color": "#9e0101"
	},
	"sugarss": {
		"name": "SugarSS",
		"color": "#2fcc9f"
	},
	"supercollider": {
		"name": "SuperCollider",
		"color": "#46390b"
	},
	"surql": {
		"name": "SurrealQL",
		"color": "#ff00a0"
	},
	"surrealql": {
		"name": "SurrealQL",
		"color": "#ff00a0"
	},
	"survex data": {
		"name": "Survex data",
		"color": "#ffcc99"
	},
	"svelte": {
		"name": "Svelte",
		"color": "#ff3e00"
	},
	"svg": {
		"name": "SVG",
		"color": "#ff9900"
	},
	"sway": {
		"name": "Sway",
		"color": "#00F58C"
	},
	"sweave": {
		"name": "Sweave",
		"color": "#198ce7"
	},
	"swift": {
		"name": "Swift",
		"color": "#F05138"
	},
	"systemverilog": {
		"name": "SystemVerilog",
		"color": "#DAE1C2"
	},
	"tab-seperated values": {
		"name": "TSV",
		"color": "#237346"
	},
	"tabular model definition language": {
		"name": "TMDL",
		"color": "#f0c913"
	},
	"tact": {
		"name": "Tact",
		"color": "#48b5ff"
	},
	"talon": {
		"name": "Talon",
		"color": "#333333"
	},
	"tcl": {
		"name": "Tcl",
		"color": "#e4cc98"
	},
	"teal": {
		"name": "Teal",
		"color": "#00B1BC"
	},
	"templ": {
		"name": "templ",
		"color": "#66D0DD"
	},
	"terra": {
		"name": "Terra",
		"color": "#00004c"
	},
	"terraform": {
		"name": "HCL",
		"color": "#844FBA"
	},
	"terraform template": {
		"name": "Terraform Template",
		"color": "#7b42bb"
	},
	"tex": {
		"name": "TeX",
		"color": "#3D6117"
	},
	"textgrid": {
		"name": "TextGrid",
		"color": "#c8506d"
	},
	"textile": {
		"name": "Textile",
		"color": "#ffe7ac"
	},
	"textmate properties": {
		"name": "TextMate Properties",
		"color": "#df66e4"
	},
	"thrift": {
		"name": "Thrift",
		"color": "#D12127"
	},
	"ti program": {
		"name": "TI Program",
		"color": "#A0AA87"
	},
	"tl-verilog": {
		"name": "TL-Verilog",
		"color": "#C40023"
	},
	"tla": {
		"name": "TLA",
		"color": "#4b0079"
	},
	"tm-properties": {
		"name": "TextMate Properties",
		"color": "#df66e4"
	},
	"tmdl": {
		"name": "TMDL",
		"color": "#f0c913"
	},
	"toit": {
		"name": "Toit",
		"color": "#c2c9fb"
	},
	"toml": {
		"name": "TOML",
		"color": "#9c4221"
	},
	"topojson": {
		"name": "JSON",
		"color": "#292929"
	},
	"tor config": {
		"name": "Tor Config",
		"color": "#59316b"
	},
	"torrc": {
		"name": "Tor Config",
		"color": "#59316b"
	},
	"tree-sitter query": {
		"name": "Tree-sitter Query",
		"color": "#8ea64c"
	},
	"troff": {
		"name": "Roff",
		"color": "#ecdebe"
	},
	"ts": {
		"name": "TypeScript",
		"color": "#3178c6"
	},
	"tsp": {
		"name": "TypeSpec",
		"color": "#4A3665"
	},
	"tsq": {
		"name": "Tree-sitter Query",
		"color": "#8ea64c"
	},
	"tsql": {
		"name": "TSQL",
		"color": "#e38c00"
	},
	"tsv": {
		"name": "TSV",
		"color": "#237346"
	},
	"tsx": {
		"name": "TSX",
		"color": "#3178c6"
	},
	"turing": {
		"name": "Turing",
		"color": "#cf142b"
	},
	"twig": {
		"name": "Twig",
		"color": "#c1d026"
	},
	"txl": {
		"name": "TXL",
		"color": "#0178b8"
	},
	"typ": {
		"name": "Typst",
		"color": "#239dad"
	},
	"typescript": {
		"name": "TypeScript",
		"color": "#3178c6"
	},
	"typescriptreact": {
		"name": "TSX",
		"color": "#3178c6"
	},
	"typespec": {
		"name": "TypeSpec",
		"color": "#4A3665"
	},
	"typst": {
		"name": "Typst",
		"color": "#239dad"
	},
	"ultisnip": {
		"name": "Vim Snippet",
		"color": "#199f4b"
	},
	"ultisnips": {
		"name": "Vim Snippet",
		"color": "#199f4b"
	},
	"unified parallel c": {
		"name": "Unified Parallel C",
		"color": "#4e3617"
	},
	"unity3d asset": {
		"name": "Unity3D Asset",
		"color": "#222c37"
	},
	"uno": {
		"name": "Uno",
		"color": "#9933cc"
	},
	"unrealscript": {
		"name": "UnrealScript",
		"color": "#a54c4d"
	},
	"untyped plutus core": {
		"name": "Untyped Plutus Core",
		"color": "#36adbd"
	},
	"ur": {
		"name": "UrWeb",
		"color": "#ccccee"
	},
	"ur/web": {
		"name": "UrWeb",
		"color": "#ccccee"
	},
	"urweb": {
		"name": "UrWeb",
		"color": "#ccccee"
	},
	"v": {
		"name": "V",
		"color": "#4f87c4"
	},
	"vala": {
		"name": "Vala",
		"color": "#a56de2"
	},
	"valve data format": {
		"name": "Valve Data Format",
		"color": "#f26025"
	},
	"vb .net": {
		"name": "Visual Basic .NET",
		"color": "#945db7"
	},
	"vb 6": {
		"name": "Visual Basic 6.0",
		"color": "#2c6353"
	},
	"vb.net": {
		"name": "Visual Basic .NET",
		"color": "#945db7"
	},
	"vb6": {
		"name": "Visual Basic 6.0",
		"color": "#2c6353"
	},
	"vba": {
		"name": "VBA",
		"color": "#867db1"
	},
	"vbnet": {
		"name": "Visual Basic .NET",
		"color": "#945db7"
	},
	"vbscript": {
		"name": "VBScript",
		"color": "#15dcdc"
	},
	"vcard": {
		"name": "vCard",
		"color": "#ee2647"
	},
	"vcl": {
		"name": "VCL",
		"color": "#148AA8"
	},
	"vdf": {
		"name": "Valve Data Format",
		"color": "#f26025"
	},
	"velocity": {
		"name": "Velocity Template Language",
		"color": "#507cff"
	},
	"velocity template language": {
		"name": "Velocity Template Language",
		"color": "#507cff"
	},
	"vento": {
		"name": "Vento",
		"color": "#ff0080"
	},
	"verilog": {
		"name": "Verilog",
		"color": "#b2b7f8"
	},
	"vhdl": {
		"name": "VHDL",
		"color": "#adb2cb"
	},
	"vim": {
		"name": "Vim Script",
		"color": "#199f4b"
	},
	"vim help file": {
		"name": "Vim Help File",
		"color": "#199f4b"
	},
	"vim script": {
		"name": "Vim Script",
		"color": "#199f4b"
	},
	"vim snippet": {
		"name": "Vim Snippet",
		"color": "#199f4b"
	},
	"vimhelp": {
		"name": "Vim Help File",
		"color": "#199f4b"
	},
	"viml": {
		"name": "Vim Script",
		"color": "#199f4b"
	},
	"vimscript": {
		"name": "Vim Script",
		"color": "#199f4b"
	},
	"virtual contact file": {
		"name": "vCard",
		"color": "#ee2647"
	},
	"visual basic": {
		"name": "Visual Basic .NET",
		"color": "#945db7"
	},
	"visual basic .net": {
		"name": "Visual Basic .NET",
		"color": "#945db7"
	},
	"visual basic 6": {
		"name": "Visual Basic 6.0",
		"color": "#2c6353"
	},
	"visual basic 6.0": {
		"name": "Visual Basic 6.0",
		"color": "#2c6353"
	},
	"visual basic classic": {
		"name": "Visual Basic 6.0",
		"color": "#2c6353"
	},
	"visual basic for applications": {
		"name": "VBA",
		"color": "#867db1"
	},
	"vlang": {
		"name": "V",
		"color": "#4f87c4"
	},
	"volt": {
		"name": "Volt",
		"color": "#1F1F1F"
	},
	"vtl": {
		"name": "Velocity Template Language",
		"color": "#507cff"
	},
	"vue": {
		"name": "Vue",
		"color": "#41b883"
	},
	"vyper": {
		"name": "Vyper",
		"color": "#9F4CF2"
	},
	"wasm": {
		"name": "WebAssembly",
		"color": "#04133b"
	},
	"wast": {
		"name": "WebAssembly",
		"color": "#04133b"
	},
	"wdl": {
		"name": "WDL",
		"color": "#42f1f4"
	},
	"web ontology language": {
		"name": "Web Ontology Language",
		"color": "#5b70bd"
	},
	"webassembly": {
		"name": "WebAssembly",
		"color": "#04133b"
	},
	"webassembly interface type": {
		"name": "WebAssembly Interface Type",
		"color": "#6250e7"
	},
	"wgsl": {
		"name": "WGSL",
		"color": "#1a5e9a"
	},
	"whiley": {
		"name": "Whiley",
		"color": "#d5c397"
	},
	"wiki": {
		"name": "Wikitext",
		"color": "#fc5757"
	},
	"wikitext": {
		"name": "Wikitext",
		"color": "#fc5757"
	},
	"winbatch": {
		"name": "Batchfile",
		"color": "#C1F12E"
	},
	"windows registry entries": {
		"name": "Windows Registry Entries",
		"color": "#52d5ff"
	},
	"wisp": {
		"name": "wisp",
		"color": "#7582D1"
	},
	"wit": {
		"name": "WebAssembly Interface Type",
		"color": "#6250e7"
	},
	"witcher script": {
		"name": "Witcher Script",
		"color": "#ff0000"
	},
	"wl": {
		"name": "Wolfram Language",
		"color": "#dd1100"
	},
	"wolfram": {
		"name": "Wolfram Language",
		"color": "#dd1100"
	},
	"wolfram lang": {
		"name": "Wolfram Language",
		"color": "#dd1100"
	},
	"wolfram language": {
		"name": "Wolfram Language",
		"color": "#dd1100"
	},
	"wollok": {
		"name": "Wollok",
		"color": "#a23738"
	},
	"workflow description language": {
		"name": "WDL",
		"color": "#42f1f4"
	},
	"world of warcraft addon data": {
		"name": "World of Warcraft Addon Data",
		"color": "#f7e43f"
	},
	"wren": {
		"name": "Wren",
		"color": "#383838"
	},
	"wrenlang": {
		"name": "Wren",
		"color": "#383838"
	},
	"wsdl": {
		"name": "XML",
		"color": "#0060ac"
	},
	"x10": {
		"name": "X10",
		"color": "#4B6BEF"
	},
	"xbase": {
		"name": "xBase",
		"color": "#403a40"
	},
	"xc": {
		"name": "XC",
		"color": "#99DA07"
	},
	"xdc": {
		"name": "Tcl",
		"color": "#e4cc98"
	},
	"xhtml": {
		"name": "HTML",
		"color": "#e34c26"
	},
	"xmake": {
		"name": "Xmake",
		"color": "#22a079"
	},
	"xml": {
		"name": "XML",
		"color": "#0060ac"
	},
	"xml property list": {
		"name": "XML Property List",
		"color": "#0060ac"
	},
	"xml+genshi": {
		"name": "Genshi",
		"color": "#951531"
	},
	"xml+kid": {
		"name": "Genshi",
		"color": "#951531"
	},
	"xojo": {
		"name": "Xojo",
		"color": "#81bd41"
	},
	"xonsh": {
		"name": "Xonsh",
		"color": "#285EEF"
	},
	"xquery": {
		"name": "XQuery",
		"color": "#5232e7"
	},
	"xsd": {
		"name": "XML",
		"color": "#0060ac"
	},
	"xsl": {
		"name": "XSLT",
		"color": "#EB8CEB"
	},
	"xslt": {
		"name": "XSLT",
		"color": "#EB8CEB"
	},
	"xten": {
		"name": "X10",
		"color": "#4B6BEF"
	},
	"xtend": {
		"name": "Xtend",
		"color": "#24255d"
	},
	"yacc": {
		"name": "Yacc",
		"color": "#4B6C4B"
	},
	"yaml": {
		"name": "YAML",
		"color": "#cb171e"
	},
	"yara": {
		"name": "YARA",
		"color": "#220000"
	},
	"yas": {
		"name": "YASnippet",
		"color": "#32AB90"
	},
	"yasnippet": {
		"name": "YASnippet",
		"color": "#32AB90"
	},
	"yml": {
		"name": "YAML",
		"color": "#cb171e"
	},
	"yul": {
		"name": "Yul",
		"color": "#794932"
	},
	"zap": {
		"name": "ZAP",
		"color": "#0d665e"
	},
	"zenscript": {
		"name": "ZenScript",
		"color": "#00BCD1"
	},
	"zephir": {
		"name": "Zephir",
		"color": "#118f9e"
	},
	"zig": {
		"name": "Zig",
		"color": "#ec915c"
	},
	"zil": {
		"name": "ZIL",
		"color": "#dc75e5"
	},
	"zimpl": {
		"name": "Zimpl",
		"color": "#d67711"
	},
	"zmodel": {
		"name": "Zmodel",
		"color": "#ff7100"
	},
	"zsh": {
		"name": "Shell",
		"color": "#89e051"
	}
};
